ПН:
  max_height: 289
  width: 340
  x: 29
  y: 89
ВТ:
  max_height: 289
  width: 340
  x: 29
  y: 446
СР:
  max_height: 289
  width: 340
  x: 29
  y: 802
ЧТ:
  max_height: 289
  width: 340
  x: 446
  y: 272
ПТ:
  max_height: 289
  width: 340
  x: 446
  y: 629
date_block:
  height: 50
  width: 160
  x: 433
  y: 142
